admin/modules/payment/controllers/AController.php
<?

namespace admin\modules\payment\controllers;

use Yii;
use yii\data\ActiveDataProvider;
use yii\widgets\ActiveForm;

use admin\modules\payment\models\Payment;
use admin\modules\shopcart\models\Order;
use admin\behaviors\SortableController;
use admin\behaviors\StatusController;

class AController extends \admin\base\admin\Controller {

    public function behaviors() {
        return [
            [
                'class' => SortableController::className(),
                'model' => Payment::className()
            ],
            [
                'class' => StatusController::className(),
                'model' => Payment::className()
            ]
        ];
    }

    public function actionIndex() {
        $data = new ActiveDataProvider([
            'query' => Payment::find()->sort(),
        ]);

        return $this->render('index', [
                    'data' => $data
        ]);
    }

    public function actionCreate() {
        $model = new Payment;

        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            } else {
                if ($model->save()) {
                    $this->flash('success', Yii::t('admin/payment', 'Способ оплаты создан'));
                    return $this->redirect(['/admin/' . $this->module->id]);
                } else {
                    $this->flash('error', Yii::t('admin', 'Ошибка. {0}', $model->formatErrors()));
                    return $this->refresh();
                }
            }
        } else {

            $model->class = "admin\modules\payment\payment_systems\Manual";

            return $this->render('create', [
                        'model' => $model
            ]);
        }
    }

    public function actionEdit($id) {
        $model = Payment::findOne($id);
        $class = $model->class;
        $model = $class::findOne($model->id);

        if ($model === null) {
            $this->flash('error', Yii::t('admin', 'Способ оплаты не найден'));
            return $this->redirect(['/admin/' . $this->module->id]);
        }

        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            } else {

                if ($model->save()) {
                    $this->flash('success', Yii::t('admin/payment', 'Способ оплаты обновлен'));
                } else {
                    $this->flash('error', Yii::t('admin', 'Ошибка при обновлении записи. {0}', $model->formatErrors()));
                }
                return $this->refresh();
            }
        } else {
            return $this->render('edit', [
                        'model' => $model
            ]);
        }
    }

    public function actionDelete($id) {
        if (($model = Payment::findOne($id))) {
            $model->delete();
        } else {
            $this->error = Yii::t('admin', 'Способ оплаты не найден');
        }
        return $this->formatResponse(Yii::t('admin/payment', 'Способ оплаты удален'));
    }

    public function actionUp($id) {
        return $this->move($id, 'up');
    }

    public function actionDown($id) {
        return $this->move($id, 'down');
    }

    public function actionOn($id) {
        return $this->changeStatus($id, Payment::STATUS_ON);
    }

    public function actionOff($id) {
        return $this->changeStatus($id, Payment::STATUS_OFF);
    }

    public function actionDefaultData($id) {
        $model = Payment::findOne($id);
        $class = $model->class;
        $model = $class::findOne($model->id);

        if ($model === null) {
            $this->flash('error', Yii::t('admin', 'Способ оплаты не найден'));
        } else {
            $model->setDefaultData();
            $model->save();
            $this->flash('success', Yii::t('admin', 'Установлены настройки по-умолчанию'));
        }
        return $this->goBack();
    }

    public function actionProcess($id) {

        $order = Order::findOne($id);

        if ($order === null) {
            $this->flash('error', Yii::t('admin', 'Запись не найдена'));
            return $this->redirect(['/admin/shopcart/a/edit', 'id' => $order->id]);
        }

        if (Yii::$app->request->post()) {
            $order->paid_status = Yii::$app->request->post('paid_status');
            $order->paid_time = time();
            $order->paid_details = 'Статус оплаты заказа изменен в панели управления на "' . $order->getPaidStatusName() . '"';

            if ($order->save()) {
                $this->flash('success', Yii::t('admin/payment', 'Статус оплаты заказа изменен'));
                Payment::adminProcessCheckout('Статус оплаты заказа изменен на "' . $order->getPaidStatusName() . '"', $order);
            } else {
                $this->flash('error', Yii::t('admin', 'Ошибка при обновлении записи. {0}', $order->formatErrors()));
                Payment::adminProcessCheckout('Ошибка при обновлении записи. {0}', $order->formatErrors(), $order);
            }
        }
        return $this->redirect(['/admin/shopcart/a/edit', 'id' => $order->id]);
    }

    public function actionTest($id) {
        $model = Payment::findOne($id);
        $class = $model->class;
        $model = $class::findOne($model->id);

        if ($model === null) {
            $this->flash('error', Yii::t('admin', 'Способ оплаты не найден'));
            return $this->redirect(['/admin/' . $this->module->id]);
        }

        if (Yii::$app->request->post()) {
            $model->test(Yii::$app->request->post('order_id'), Yii::$app->request->post('amount'));
            $this->flash('warning', Yii::t('admin', 'HTTP-уведомление отправлено'));
        }
        return $this->redirect(['/admin/payment/a/edit', 'id' => $id]);
    }

}

admin/modules/payment/views/a/_form.php
<?

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use admin\widgets\Redactor;

$module = $this->context->module->id;
?>
<?
$form = ActiveForm::begin([
            'enableAjaxValidation' => true,
            'options' => ['enctype' => 'multipart/form-data', 'class' => 'model-form']
        ]);
?>
<?= $form->field($model, 'title') ?>
<?= $form->field($model, 'slug') ?>
<?= $form->field($model, 'class') ?>
<small>
    <p>
        admin\modules\payment\payment_systems\Manual - <?= Yii::t('admin', 'без онлайн-оплаты, статус оплачено меняется только через Панель управления') ?>
    </p>
    <p>
        admin\modules\payment\payment_systems\YandexMoney - <?= Yii::t('admin', 'прием денег через кошелек Яндекс.Деньги') ?>
    </p>
    <p>
        admin\modules\payment\payment_systems\YandexKassa - <?= Yii::t('admin', 'оплата через ПШ Яндекс.Касса') ?>
    </p>
</small>
<?= $form->field($model, 'is_manual')->checkbox() ?>
<?= $form->field($model, 'available_to') ?>
<?=
$form->field($model, 'description')->widget(Redactor::className(), [
    'options' => [
        'imageUpload' => Url::to(['/admin/redactor/upload', 'dir' => 'catalog'], true),
        'fileUpload' => Url::to(['/admin/redactor/upload', 'dir' => 'catalog'], true),
    ]
])
?>

<? $model->renderDataForm(); ?>


<div class="row">
    <div class="col-md-6">
        <?= Html::submitButton(Yii::t('admin', 'Сохранить'), ['class' => 'btn btn-primary']) ?>
    </div>
    <div class="col-md-4">
        
    </div>
    <div class="col-md-2">
        <? if (Yii::$app->user->can("SuperAdmin")) { ?> <a href="<?= Url::to(['/admin/payment/a/default-data', 'id' => $model->id]) ?>" class="btn btn-warning  btn-block"><i class="fa fa-flash"></i> <?= Yii::t('admin', 'Настройки по-умолчанию') ?></a><? } ?>
    </div>
</div>
<? ActiveForm::end(); ?>
<? if (Yii::$app->user->can("SuperAdmin")) { ?> 
    <div class="row mt-75">
        <?= Html::beginForm(Url::to(['/admin/payment/a/test', 'id' => $model->id]), 'post') ?>
        <div class="col-md-6">

        </div>
        <div class="col-md-2">
            <?= Html::input('text', 'amount', '', ['class' => 'form-control', 'placeholder' => Yii::t('admin', 'Сумма заказа')]) ?>
        </div>
        <div class="col-md-2">
            <?= Html::input('text', 'order_id', '', ['class' => 'form-control', 'placeholder' => Yii::t('admin', 'Номер заказа')]) ?>
        </div>
        <div class="col-md-2">
            <?= Html::submitButton(Yii::t('admin', 'Тестовая оплата заказа'), ['class' => 'btn btn-danger btn-block']) ?>            
        </div>
        <?= Html::endForm() ?>
    </div>
<? } ?>

admin/modules/payment/views/a/_menu.php
<?
use yii\helpers\Url;

$action = $this->context->action->id;
$module = $this->context->module->id;
?>
<ul class="nav nav-pills">
    <li <?= ($action === 'index') ? 'class="active"' : '' ?>>
        <a href="<?= Url::to('/admin/' . $module) ?>">
            <? if($action == 'edit' || $action == 'photos') : ?>
                <i class="glyphicon glyphicon-chevron-left fs-12"></i>
            <? endif; ?>
            <?= Yii::t('admin', 'Список') ?>
        </a>
    </li>
    <li <?= ($action === 'create') ? 'class="active"' : '' ?>><a href="<?= Url::to(['/admin/'.$module.'/a/create']) ?>"><?= Yii::t('admin', 'Создать') ?></a></li>
</ul>
<br>

admin/modules/payment/views/a/_submenu.php
<?
use yii\helpers\Url;

$action = $this->context->action->id;
$module = $this->context->module->id;
?>

<ul class="nav nav-tabs">
    <li <?= ($action === 'edit') ? 'class="active"' : '' ?>><a href="<?= Url::to(['/admin/'.$module.'/a/edit', 'id' => $model->primaryKey]) ?>"><?= Yii::t('admin/payment', 'Редактировать службы доставки') ?></a></li>
</ul>
<br>

admin/modules/payment/views/a/create.php
<?
$this->title = Yii::t('admin/payment', 'Редактировать службу доставки');
?>
<?= $this->render('_menu') ?>
<?= $this->render('_form', ['model' => $model]) ?>

admin/modules/payment/views/a/edit.php
<?
$this->title = $model->title;
?>
<?= $this->render('_menu') ?>

<? if($this->context->module->settings['enablePhotos']) echo $this->render('_submenu', ['model' => $model]) ?>

<?= $this->render('_form', ['model' => $model]) ?>

admin/modules/payment/views/a/index.php
<?

use admin\modules\payment\models\Payment;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = Yii::t('admin/payment', 'Способы оплаты');

$module = $this->context->module->id;
?>

<?= $this->render('_menu') ?>

<? if ($data->count > 0) : ?>
    <table class="table table-hover">
        <thead>
            <tr>
                <th width="50">#</th>
                <th><?= Yii::t('admin', 'Название') ?></th>
                <th width="100"><?= Yii::t('admin', 'Статус') ?></th>
                <th width="120"></th>
            </tr>
        </thead>
        <tbody>
            <? foreach ($data->models as $item) : ?>
                <tr data-id="<?= $item->primaryKey ?>">
                    <td><?= $item->primaryKey ?></td>
                    <td><a href="<?= Url::to(['/admin/' . $module . '/a/edit', 'id' => $item->primaryKey]) ?>"><?= $item->title ?></a></td>
                    <td class="status">
                        <?=
                        Html::checkbox('', $item->status == Payment::STATUS_ON, [
                            'class' => 'switch',
                            'data-id' => $item->primaryKey,
                            'data-link' => Url::to(['/admin/' . $module . '/a']),
                        ])
                        ?>
                    </td>
                    <td>
                        <div class="btn-group btn-group-sm" role="group">
                            <a href="<?= Url::to(['/admin/' . $module . '/a/up', 'id' => $item->primaryKey]) ?>" class="btn btn-default move-up" title="<?= Yii::t('admin', 'Переместить вверх') ?>"><span class="fa fa-arrow-up"></span></a>
                            <a href="<?= Url::to(['/admin/' . $module . '/a/down', 'id' => $item->primaryKey]) ?>" class="btn btn-default move-down" title="<?= Yii::t('admin', 'Переместить вниз') ?>"><span class="fa fa-arrow-down"></span></a>
                            <a href="<?= Url::to(['/admin/' . $module . '/a/delete', 'id' => $item->primaryKey]) ?>" class="btn btn-default text-red" title="<?= Yii::t('admin', 'Удалить запись') ?>"><span class="fa fa-times"></span></a>
                        </div>
                    </td>
                </tr>
            <? endforeach; ?>
        </tbody>
    </table>
    <?=
    yii\widgets\LinkPager::widget([
        'pagination' => $data->pagination
    ])
    ?>
<? else : ?>
    <p><?= Yii::t('admin', 'Записи не найдены') ?></p>
<? endif; ?>

admin/modules/payment/views/a/photos.php
<?
use admin\widgets\Photos;

$this->title = $model->title;
?>

<?= $this->render('_menu') ?>
<?= $this->render('_submenu', ['model' => $model]) ?>

<?= Photos::widget(['model' => $model])?>