admin/modules/shopcart/models/Order.php
<?

namespace admin\modules\shopcart\models;

use Yii;
use admin\behaviors\CalculateNotice;
use admin\helpers\Mail;
use admin\models\Setting;
use admin\validators\EscapeValidator;
use yii\helpers\Url;

class Order extends \admin\base\ActiveRecordData {

    const PAID_STATUS_NOT_PAID = 0;
    const PAID_STATUS_PAID = 1;
    const STATUS_BLANK = 0;
    const STATUS_PENDING = 1;
    const STATUS_PROCESSED = 2;
    const STATUS_DECLINED = 3;
    const STATUS_SENT = 4;
    const STATUS_RETURNED = 5;
    const STATUS_ERROR = 6;
    const STATUS_COMPLETED = 7;
    const SESSION_KEY = 'admin_module_shopcart_at';

    public static function tableName() {
        return 'admin_module_shopcart_orders';
    }

    public function rules() {
        return [            
            ['name', 'required', 'when' => function($model) {
                    return $model->scenario == 'confirm' && Yii::$app->getModule('admin')->activeModules['shopcart']->settings['enableName'];
                }],
            ['phone', 'required', 'when' => function($model) {
                    return $model->scenario == 'confirm' && Yii::$app->getModule('admin')->activeModules['shopcart']->settings['enablePhone'];
                }],
            [['name', 'address', 'phone', 'comment'], 'trim'],
            ['email', 'email'],
            [['user_id', 'delivery_id', 'payment_id'], 'integer'],
            ['name', 'string', 'max' => 32],
            ['address', 'string', 'max' => 1024],
            ['phone', 'string', 'max' => 32],
            ['phone', 'match', 'pattern' => '/^[\d\s-\+\(\)]+$/'],
            ['comment', 'string', 'max' => 1024],
            [['name', 'address', 'phone', 'comment'], EscapeValidator::className()],
        ];
    }

    public function attributeLabels() {
        return [
            'name' => Yii::t('admin', 'Имя'),
            'email' => Yii::t('admin', 'E-mail'),
            'address' => Yii::t('admin', 'Адрес'),
            'phone' => Yii::t('admin', 'Телефон'),
            'comment' => Yii::t('admin', 'Комментарий'),
            'remark' => Yii::t('admin/shopcart', 'Комментарий сотрудника'),
        ];
    }

    public function behaviors() {
        return [
            'cn' => [
                'class' => CalculateNotice::className(),
                'callback' => function() {
                    return self::find()->where(['new' => 1])->count();
                }
                    ]
                ];
            }

            public static function statusName($status) {
                $states = self::states();
                return !empty($states[$status]) ? $states[$status] : $status;
            }

            public static function states() {
                return [
                    self::STATUS_BLANK => Yii::t('admin/shopcart', 'Корзина'),
                    self::STATUS_PENDING => Yii::t('admin/shopcart', 'В обработке'),
                    self::STATUS_PROCESSED => Yii::t('admin/shopcart', 'Обработан'),
                    self::STATUS_DECLINED => Yii::t('admin/shopcart', 'Отменен'),
                    self::STATUS_SENT => Yii::t('admin/shopcart', 'Отправлен'),
                    self::STATUS_RETURNED => Yii::t('admin/shopcart', 'Возврат'),
                    self::STATUS_ERROR => Yii::t('admin/shopcart', 'Ошибка'),
                    self::STATUS_COMPLETED => Yii::t('admin/shopcart', 'Выполнен'),
                ];
            }

            public function isPaid() {
                return (int) $this->paid_status === static::PAID_STATUS_PAID;
            }

            public function isNotPaid() {
                return (int) $this->paid_status === static::PAID_STATUS_NOT_PAID;
            }

            public static function paidStatusName($paidStatus) {
                $paidStates = self::paidStates();
                return !empty($paidStates[$paidStatus]) ? $paidStates[$paidStatus] : $paidStatus;
            }

            public static function paidStates() {
                return [
                    self::PAID_STATUS_NOT_PAID => Yii::t('admin/shopcart', 'Не оплачен'),
                    self::PAID_STATUS_PAID => Yii::t('admin/shopcart', 'Оплачен'),
                ];
            }

            public function getStatusName() {
                $states = self::states();
                return !empty($states[$this->status]) ? $states[$this->status] : $this->status;
            }

            public function renderStatus() {
                if ($this->status == self::STATUS_PENDING) {
                    return '<span class="label label-primary">' . $this->getStatusName() . '</span>';
                }
                if ($this->status == self::STATUS_PROCESSED) {
                    return '<span class="label label-success">' . $this->getStatusName() . '</span>';
                }
                return '<span class="label label-default">' . $this->getStatusName() . '</span>';
            }

            public function getPaidStatusName() {
                $paidStates = self::paidStates();
                return !empty($paidStates[$this->paid_status]) ? $paidStates[$this->paid_status] : $this->paid_status;
            }

            public function renderPaidStatus() {
                if ($this->paid_status == self::PAID_STATUS_PAID) {
                    return '<span class="label label-success">' . $this->getPaidStatusName() . '</span>';
                }
                return '<span class="label label-default">' . $this->getPaidStatusName() . '</span>';
            }

            public function getGoods() {
                return $this->hasMany(Good::className(), ['order_id' => 'id']);
            }

            public function getCost() {
                $total = 0;
                foreach ($this->goods as $good) {
                    $total += $good->count * round($good->price * (1 - $good->discount / 100));
                }

                return $total;
            }

            public function getTotalCost() {
                return $this->cost + $this->delivery_cost;
            }

            public function beforeSave($insert) {
                if (parent::beforeSave($insert)) {
                    if ($insert) {
                        $this->ip = Yii::$app->request->userIP;
                        $this->access_token = Yii::$app->security->generateRandomString(32);
                        $this->time = time();
                    } else {
                        if ($this->oldAttributes['status'] == self::STATUS_BLANK && $this->status == self::STATUS_PENDING) {
                            $this->new = 1;
                            $this->notifyAdmin();
                            $this->notifyUser();
                        }
                    }
                    return true;
                } else {
                    return false;
                }
            }

            public function afterDelete() {
                parent::afterDelete();

                foreach ($this->getGoods()->all() as $good) {
                    $good->delete();
                }
            }

            public function notifyAdmin() {
                $settings = Yii::$app->getModule('admin')->activeModules['shopcart']->settings;

                if (!$settings['notifyAdmin']) {
                    return false;
                }
                return Mail::send(
                                Setting::get('contact_email'), str_replace('##order_id##', $this->id, $settings['subjectNotifyAdmin']), $settings['templateNotifyAdmin'], [
                            'order' => $this,
                            'link' => Url::to(['/admin/shopcart/a/edit', 'id' => $this->primaryKey], true),
                                ]
                );
            }

            public function notifyUser() {
                if ($this->email) {
                    $settings = Yii::$app->getModule('admin')->activeModules['shopcart']->settings;

                    return Mail::send(
                                    $this->email, str_replace('##order_id##', $this->id, $settings['subjectNotifyUser']), $settings['templateNotifyUser'], [
                                'order' => $this,
                                'link' => Url::to([$settings['frontendShopcartOrderRoute'], 'id' => $this->primaryKey, 'token' => $this->access_token], true),
                                    ]
                    );
                }
            }

        }
        

admin/modules/shopcart/controllers/AController.php
<?

namespace admin\modules\shopcart\controllers;

use Yii;
use yii\data\ActiveDataProvider;

use admin\modules\shopcart\models\Good;
use admin\modules\shopcart\models\Order;

class AController extends \admin\base\admin\Controller {

    public $all = 0;
    public $pending = 0;
    public $processed = 0;
    public $sent = 0;

    public function init() {
        parent::init();

        $this->all = Order::find()->where(['<>','status',(int)Order::STATUS_BLANK])->count();
        $this->pending = Order::find()->status(Order::STATUS_PENDING)->count();
        $this->processed = Order::find()->status(Order::STATUS_PROCESSED)->count();
        $this->sent = Order::find()->status(Order::STATUS_SENT)->count();
    }

    public function actionIndex() {
        return $this->render('index', [
                    'data' => new ActiveDataProvider([
                        'query' => Order::find()->with('goods')->where(['<>','status',(int)Order::STATUS_BLANK])->desc(),
                        'totalCount' => $this->all
                            ])
        ]);
    }

    public function actionPending() {
        return $this->render('index', [
                    'data' => new ActiveDataProvider([
                        'query' => Order::find()->with('goods')->status(Order::STATUS_PENDING)->desc(),
                        'totalCount' => $this->pending
                            ])
        ]);
    }
    
    public function actionProcessed() {
        return $this->render('index', [
                    'data' => new ActiveDataProvider([
                        'query' => Order::find()->with('goods')->status(Order::STATUS_PROCESSED)->desc(),
                        'totalCount' => $this->processed
                            ])
        ]);
    }

    public function actionSent() {
        return $this->render('index', [
                    'data' => new ActiveDataProvider([
                        'query' => Order::find()->with('goods')->status(Order::STATUS_SENT)->desc(),
                        'totalCount' => $this->sent
                            ])
        ]);
    }

    public function actionCompleted() {
        return $this->render('index', [
                    'data' => new ActiveDataProvider([
                        'query' => Order::find()->with('goods')->status(Order::STATUS_COMPLETED)->desc()
                            ])
        ]);
    }

    public function actionFails() {
        return $this->render('index', [
                    'data' => new ActiveDataProvider([
                        'query' => Order::find()->with('goods')->where(['in', 'status', [Order::STATUS_DECLINED, Order::STATUS_ERROR, Order::STATUS_RETURNED]])->desc()
                            ])
        ]);
    }

    public function actionBlank() {
        return $this->render('index', [
                    'data' => new ActiveDataProvider([
                        'query' => Order::find()->with('goods')->status(Order::STATUS_BLANK)->desc()
                            ])
        ]);
    }

    public function actionEdit($id) {
        $request = Yii::$app->request;

        $orderFormClass = '\\' . APP_NAME . '\models\OrderForm';
        $orderForm = new $orderFormClass();

        $order = Order::findOne($id);

        if ($order === null) {
            $this->flash('error', Yii::t('admin', 'Запись не найдена'));
            return $this->redirect(['/admin/' . $this->module->id]);
        }


        if ($request->post('status')) {
            $newStatus = $request->post('status');
            $oldStatus = $order->status;

            $order->status = $newStatus;
            $order->remark = filter_var($request->post('remark'), FILTER_SANITIZE_STRING);

            if ($order->save()) {
                if ($newStatus != $oldStatus && $request->post('notify')) {
                    $order->notifyUser();
                }
                $this->flash('success', Yii::t('admin/shopcart', 'Заказ обновлен'));
            } else {
                $this->flash('error', Yii::t('admin', 'Ошибка при обновлении записи. {0}', $order->formatErrors()));
            }
            return $this->refresh();
        } else {
            if ($order->new > 0) {
                $order->new = 0;
                $order->update();
            }
            $order = Order::findOne($id);
            $goods = Good::find()->where(['order_id' => $order->primaryKey])->with('item')->asc()->all();

            return $this->render('edit', [
                        'order' => $order,
                        'goods' => $goods,
                        'orderForm' => $orderForm
            ]);
        }
    }

    public function actionDelete($id) {
        if (($model = Order::findOne($id))) {
            $model->delete();
        } else {
            $this->error = Yii::t('admin', 'Запись не найдена');
        }
        return $this->formatResponse(Yii::t('admin/shopcart', 'Заказ удален'));
    }

    public function actionData($id) {

        $order = Order::findOne($id);

        if ($order === null) {
            $this->flash('error', Yii::t('admin', 'Запись не найдена'));
            return $this->redirect(['/admin/' . $this->module->id . '/a/edit', 'id' => $order->id]);
        }

        if (is_array(Yii::$app->request->post('data'))) {
            $order->data = Yii::$app->request->post('data');
            if ($order->save()) {
                $this->flash('success', Yii::t('admin/shopcart', 'Дополнительные данные заказа обновлены'));
                return $this->redirect(['/admin/shopcart/a/edit', 'id' => $order->id]);
            }
        }
        $this->flash('error', Yii::t('admin', 'Ошибка при обновлении записи. {0}', $order->formatErrors()));
        return $this->redirect(['/admin/shopcart/a/edit', 'id' => $order->id]);
    }

    public function actionExportToExcel($id) {

        $order = Order::findOne($id);

        if ($order === null) {
            $this->flash('error', Yii::t('admin', 'Запись не найдена'));
            return $this->redirect(['/admin/' . $this->module->id . '/a/edit', 'id' => $order->id]);
        }

        $class = Yii::$app->getModule('admin')->activeModules['shopcart']->settings['modelExportOrderToExcel'];
        
        $orderToExcel = new $class();
        $orderToExcel->export($order);
        
    }

}

admin/modules/shopcart/controllers/GoodsController.php
<?
namespace admin\modules\shopcart\controllers;

use Yii;

use admin\modules\shopcart\models\Good;

class GoodsController extends \admin\base\admin\Controller
{
    public function actionDelete($id)
    {
        if(($model = Good::findOne($id))){
            $model->delete();
        } else {
            $this->error = Yii::t('admin', 'Запись не найдена');
        }
        return $this->formatResponse(Yii::t('admin/shopcart', 'Позиция удалена из заказа'));
    }
}

admin/modules/shopcart/views/a/_menu.php
<?
use yii\helpers\Url;

$action = $this->context->action->id;
$module = $this->context->module->id;

$backTo = null;
$indexUrl = Url::to(['/admin/'.$module]);
$pendingUrl = Url::to(['/admin/'.$module.'/a/pending']);
$processedUrl = Url::to(['/admin/'.$module.'/a/processed']);
$sentUrl = Url::to(['/admin/'.$module.'/a/sent']);
$completedUrl = Url::to(['/admin/'.$module.'/a/completed']);
$failsUrl = Url::to(['/admin/'.$module.'/a/fails']);
$blankUrl = Url::to(['/admin/'.$module.'/a/blank']);
?>
<ul class="nav nav-pills">
    <li <?= ($action === 'index') ? 'class="active"' : '' ?>>
        <a href="<?= $indexUrl ?>">
            <? if($backTo === 'index') : ?>
                <i class="glyphicon glyphicon-chevron-left fs-12"></i>
            <? endif; ?>
            <?= Yii::t('admin/shopcart', 'Все') ?>
            <? if($this->context->all > 0) : ?>
                <span class="badge"><?= $this->context->all ?></span>
            <? endif; ?>
        </a>
    </li>
    <li <?= ($action === 'pending') ? 'class="active"' : '' ?>>
        <a href="<?= $pendingUrl ?>">
            <? if($backTo === 'pending') : ?>
                <i class="glyphicon glyphicon-chevron-left fs-12"></i>
            <? endif; ?>
            <?= Yii::t('admin/shopcart', 'В обработке') ?>
            <? if($this->context->pending > 0) : ?>
                <span class="badge"><?= $this->context->pending ?></span>
            <? endif; ?>
        </a>
    </li>
    <li <?= ($action === 'processed') ? 'class="active"' : '' ?>>
        <a href="<?= $processedUrl ?>">
            <? if($backTo === 'processed') : ?>
                <i class="glyphicon glyphicon-chevron-left fs-12"></i>
            <? endif; ?>
            <?= Yii::t('admin/shopcart', 'Обработан') ?>
            <? if($this->context->processed > 0) : ?>
                <span class="badge"><?= $this->context->processed ?></span>
            <? endif; ?>
        </a>
    </li>
    <li <?= ($action === 'sent') ? 'class="active"' : '' ?>>
        <a href="<?= $sentUrl ?>">
            <? if($backTo === 'sent') : ?>
                <i class="glyphicon glyphicon-chevron-left fs-12"></i>
            <? endif; ?>
            <?= Yii::t('admin/shopcart', 'Отправлен') ?>
            <? if($this->context->sent > 0) : ?>
                <span class="badge"><?= $this->context->sent ?></span>
            <? endif; ?>
        </a>
    </li>
    <li <?= ($action === 'completed') ? 'class="active"' : '' ?>>
        <a href="<?= $completedUrl ?>">
            <? if($backTo === 'completed') : ?>
                <i class="glyphicon glyphicon-chevron-left fs-12"></i>
            <? endif; ?>
            <?= Yii::t('admin/shopcart', 'Выполнен') ?>
        </a>
    </li>
    <li <?= ($action === 'fails') ? 'class="active"' : '' ?>>
        <a href="<?= $failsUrl ?>">
            <? if($backTo === 'fails') : ?>
                <i class="glyphicon glyphicon-chevron-left fs-12"></i>
            <? endif; ?>
            <?= Yii::t('admin/shopcart', 'Ошибка') ?>
        </a>
    </li>
    <li <?= ($action === 'blank') ? 'class="active"' : '' ?>>
        <a href="<?= $blankUrl ?>">
            <? if($backTo === 'blank') : ?>
                <i class="glyphicon glyphicon-chevron-left fs-12"></i>
            <? endif; ?>
            <?= Yii::t('admin/shopcart', 'Корзины') ?>
        </a>
    </li>
</ul>
<br>

admin/modules/shopcart/views/a/edit.php
<?

use admin\modules\shopcart\models\Order;
use yii\helpers\Html;
use yii\helpers\Url;
use admin\helpers\Image;
use admin\modules\payment\models\Checkout;

$this->title = Yii::t('admin/shopcart', 'Заказ') . ' №' . $order->primaryKey;

$states = Order::states();
unset($states[Order::STATUS_BLANK]);

$paidStates = Order::paidStates();

$module = $this->context->module->id;

$this->registerJs('
var oldStatus = ' . $order->status . ';
$("#order-status").change(function(){
    if($(this).val() != oldStatus){
        $("#notify-user").slideDown();
    } else {
        $("#notify-user").slideUp();
    }
});
');
?>
<?= $this->render('_menu') ?>
<div class="row">
    <div class="col-md-6">
        <h3><?= Yii::t('admin/shopcart', 'Данные заказа') ?> <i class="fa fa-file-text"></i></h3>
        <hr>
        <?= Html::beginForm(Url::to(['/admin/shopcart/a/edit', 'id' => $order->id]), 'post', ['class' => 'form-horizontal']) ?>
        <? if ($order->status != Order::STATUS_BLANK) : ?>
            <div class="form-group">
                <label class="control-label col-md-2"><?= Yii::t('admin', 'Статус заказа') ?></label>
                <div class="col-md-10"><?= Html::dropDownList('status', $order->status, $states, ['id' => 'order-status', 'class' => 'form-control']) ?></div>
            </div>
        <? endif; ?>
        <? if ($order->email) : ?>
            <div class="form-group">
                <label class="control-label col-md-2"></label>
                <div class="col-md-8">
                    <div class="checkbox" id="notify-user" style="display: none;">
                        <label>
                            <?= Html::checkbox('notify', true, ['uncheck' => 0]) ?> <?= Yii::t('admin/shopcart', 'Отправить письмо с уведомлением пользователю') ?>
                        </label>
                    </div>
                </div>
            </div>
        <? endif; ?>
        <div class="form-group">
            <label class="control-label col-md-2"><?= Yii::t('admin', 'E-mail') ?></label>
            <div class="col-md-10"><p class="form-control-static"><?= $order->email ?></p></div>
        </div>
        <? if ($this->context->module->settings['enablePhone']) : ?>
            <div class="form-group">
                <label class="control-label col-md-2"><?= Yii::t('admin/shopcart', 'Телефон') ?></label>
                <div class="col-md-10"><p class="form-control-static"><?= $order->phone ?></p></div>
            </div>
        <? endif; ?>
        <? if ($this->context->module->settings['enableName']) : ?>
            <div class="form-group">
                <label class="control-label col-md-2"><?= Yii::t('admin', 'Имя') ?></label>
                <div class="col-md-10"><p class="form-control-static"><?= $order->name ?></p></div>
            </div>
        <? endif; ?> 
        <div class="form-group">
            <label class="control-label col-md-2"><?= Yii::t('admin', 'Адрес') ?></label>
            <div class="col-md-10"><p class="form-control-static"><?= $order->address ?></p></div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2"><?= Yii::t('admin', 'Дата заказа') ?></label>
            <div class="col-md-10"><p class="form-control-static"><?= Yii::$app->formatter->asDatetime($order->time, 'medium') ?></p></div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">IP</label>
            <div class="col-md-10"><p class="form-control-static"><?= $order->ip ?> <a href="//freegeoip.net/?q=<?= $order->ip ?>" class="label label-info" target="_blank">info</a></p></div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2"><?= Yii::t('admin/shopcart', 'Комментарий клиента') ?></label>
            <div class="col-md-10"><p class="form-control-static"><?= nl2br($order->comment) ?></p></div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2"><?= Yii::t('admin/shopcart', 'Комментарий сотрудника') ?></label>
            <div class="col-md-10"><?= Html::textarea('remark', $order->remark, ['class' => 'form-control']) ?></div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2"></label>
            <div class="col-md-10"></div>
        </div>

        <?= Html::submitButton(Yii::t('admin', 'Сохранить'), ['class' => 'btn btn-primary']) ?>

        <?= Html::endForm() ?>
    </div>
    <div class="col-md-6">
        <h3><?= Yii::t('admin/shopcart', 'Состояние оплаты') ?> <i class="fa fa-money"></i></h3>
        <hr>

        <?= Html::beginForm(Url::to(['/admin/payment/a/process', 'id' => $order->id]), 'post', ['class' => 'form-horizontal']) ?>
        <div class="form-group">
            <label class="control-label col-md-2"><?= Yii::t('admin', 'Статус оплаты') ?></label>
            <div class="col-md-8"><?= Html::dropDownList('paid_status', $order->paid_status, $paidStates, ['class' => 'form-control']) ?></div>
            <div class="col-md-2"><?= Html::submitButton(Yii::t('admin', 'Сохранить'), ['class' => 'btn btn-primary']) ?></div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2"><?= Yii::t('admin', 'Способ оплаты') ?></label>
            <div class="col-md-10"><p class="form-control-static"><i class="fa fa-fw fa-money"></i> <?= $order->payment_details ?></p></div>
        </div>
        <? if ($order->paid_time) { ?>
            <div class="form-group">
                <label class="control-label col-md-2"><?= Yii::t('admin', 'Время оплаты') ?></label>
                <div class="col-md-10"><p class="form-control-static"><?= Yii::$app->formatter->asDatetime($order->paid_time, 'short') ?></p></div>
            </div>
        <? } ?>
        <? if ($order->paid_details) { ?>
            <div class="form-group">
                <label class="control-label col-md-2"><?= Yii::t('admin', 'Детали оплаты') ?></label>
                <div class="col-md-10"><p class="form-control-static"><?= $order->paid_details ?></p></div>
            </div> 
        <? } ?>


        <div class="row">
            <label class="control-label col-md-2"><?= Yii::t('admin', 'Платежи') ?></label>
            <div class="col-md-10">
                <div class="form-control-static">
                    <? foreach (Checkout::getByOrderId($order->id) as $checkout) { ?>
                        <i class="fa fa-caret-right"></i>
                        <?= Yii::$app->formatter->asDatetime($checkout->time, 'short') ?>
                        <?= $checkout->renderStatus() ?> <?= $checkout->description ?>
                        <a href="javascript:void(0);" data-toggle="modal" data-target="#requestModal_<?= $checkout->id ?>"><i class="fa fa-info-circle"></i></a>       
                        <?= $checkout->renderModal('requestModal_' . $checkout->id) ?>
                        <br>
                    <? } ?> 
                </div>
            </div>                
        </div>

        <?= Html::endForm() ?>
    </div>
</div>
<hr>
<h3><?= Yii::t('admin/shopcart', 'Список товаров') ?> <i class="fa fa-shopping-cart"></i></h3>
<hr>
<table class="table table-bordered">
    <thead>
    <th></th>
    <th><?= Yii::t('admin', 'Описание') ?></th>
    <th><?= Yii::t('admin/shopcart', 'Опции') ?></th>
    <th width="80"><?= Yii::t('admin/shopcart', 'Кол-во') ?></th>
    <th width="80"><?= Yii::t('admin/shopcart', 'Скидка') ?></th>
    <th width="150"><?= Yii::t('admin/shopcart', 'Цена') ?></th>
    <th width="30"></th>
</thead>
<tbody>
    <?
    $goods_total_count = 0;
    foreach ($goods as $good) {
        $goods_total_count += $good->count;
        ?>
        <tr>
            <td width="50px"><img src="<?= Image::thumb($good->item->image, 45); ?>"></td>
            <td><?= Html::a($good->item->title, ['/admin/catalog/item/edit', 'id' => $good->item->primaryKey]) ?></td>
            <td><?= $good->options ?></td>
            <td><?= $good->count ?></td>
            <td><?= $good->discount ?></td>
            <td>
                <? if ($good->discount) { ?>
                    <b><?= round($good->price * (1 - $good->discount / 100)) ?> <i class="fas fa-ruble-sign"></i></b>
        <strike><small class="text-muted"><?= $good->price ?></small></strike>
    <? } else { ?>
        <b><?= $good->price ?> <i class="fas fa-ruble-sign"></i></b>
    <? } ?>
    </td>
    <td><a href="<?= Url::to(['/admin/' . $module . '/goods/delete', 'id' => $good->primaryKey]) ?>" class="fa fa-times text-red" title="<?= Yii::t('admin', 'Удалить запись') ?>"></a></td>
    </tr>
<? } ?>
</tbody>
</table>
<h4 class="text-right"><?= Yii::t('admin/shopcart', 'Стоимость {goods_total_count} товара(ов):', ['goods_total_count' => $goods_total_count]) ?> <?= $order->cost ?> <i class="fas fa-ruble-sign"></i></h4>

<?
//Дополнительные данные заказа
$str = '';
foreach ($orderForm->attributes as $key => $value) {

    if ($order->data) {
        foreach ($order->data as $data_key => $data_value) {
            if ($data_key == $key) {
                if (is_array($data_value)) {
                    $str .= '<td><span class="text-muted">' . $orderForm->getAttributeLabel($key) . '</span><br>';
                    foreach ($data_value as $data_value_key => $data_value_value) {
                        $str .= Html::input('text', 'data[' . $key . '][' . $data_value_key . ']', $data_value_value, ['class' => 'form-control input-sm', 'maxlength' => 512]);
                    }
                    $str .= '</td>';
                } else {
                    $str .= '<td><span class="text-muted">' . $orderForm->getAttributeLabel($key) . '</span><br>' .
                            Html::input('text', 'data[' . $key . ']', $data_value, ['class' => 'form-control input-sm', 'maxlength' => 512]) .
                            '</td>';
                }
            }
        }
    }
    ?>

    <?
}

if ($str) {
    ?>
    <div class="row">
        <div class="col-md-12">        
            <h3><?= Yii::t('admin/shopcart', 'Дополнительные данные заказа') ?> <i class="fa fa-cart-plus"></i></h3>
            <hr>            
            <?= Html::beginForm(Url::to(['/admin/shopcart/a/data', 'id' => $order->id]), 'post') ?>
            <table class="table">
                <tbody>
                    <tr>
                        <?= $str ?>
                    </tr>  
                </tbody>
            </table>
            <?= Html::submitButton(Yii::t('admin', 'Сохранить дополнительные данные'), ['class' => 'btn btn-primary']) ?>
            <?= Html::endForm() ?>            
        </div>
    </div>
<? } ?>
<div class="row">
    <div class="col-md-12">
        <h3><?= Yii::t('admin/shopcart', 'Служба доставки') ?> <i class="fa fa-truck"></i></h3>
        <hr>
        <?= $order->delivery_details ?> - <?= $order->delivery_cost ?> <i class="fas fa-ruble-sign"></i>        
    </div>    
</div>
<div class="row">
    <div class="col-md-12 text-right">
        <h3><?= Yii::t('admin/shopcart', 'Итого стоимость заказа: ') ?> <?= $order->totalCost ?> <i class="fas fa-ruble-sign"></i></h3>
    </div>
</div>

<?= Html::beginForm(Url::to(['/admin/shopcart/a/export-to-excel', 'id' => $order->id]), 'post') ?>
<div class="row">
    <div class="col-md-12">
        <?= Html::submitButton('<span class="fa fa-file-excel"></span> ' . Yii::t('admin', 'Экспорт заказа в excel файл'), ['class' => 'btn btn-primary btn-success']) ?>       
    </div>
</div>
<?= Html::endForm() ?>      