admin/modules/yml/models/Export.php
<?

namespace admin\modules\yml\models;

use Yii;
use yii\helpers\FileHelper;
use admin\modules\catalog\models\Category;
use admin\modules\yml\widgets\Excel;
use admin\modules\yml\YmlModule;

/**
 *
 * @property integer $id
 * @property string $title
 * @property string $data
 *
 */
class Export extends \admin\base\ActiveRecord {

    public $count = 0;
    public $class = 'admin\modules\yml\external_export\Shop';
    public $brands = [];
    public $categories = [];
    public $items = [];
    public $to_excel = false;
    public $status = '1';
    public $shop_name;
    public $shop_company;
    public $shop_url;
    public $shop_agency;
    public $shop_email;
    public $shop_cpa;
    public $all_delivery_options_cost = 0;
    public $all_delivery_options_days = '1-2';
    public $delivery_free_from = 2500;
    public $delivery_options_cost = 350;
    public $delivery_options_days = '1-2';
    public $asAttachment = true;

    public static function tableName() {
        return 'admin_module_yml_export';
    }

    public function rules() {
        return [
                [['title', 'shop_name', 'shop_company', 'shop_url', 'all_delivery_options_cost', 'all_delivery_options_days', 'delivery_free_from', 'delivery_options_cost', 'delivery_options_days'], 'required'],
                ['title', 'unique'],
                [['class'], 'required'],
                ['class', 'string', 'max' => 512],
                ['class', 'checkExists'],
                ['count', 'integer'],
                ['count', 'default', 'value' => 0],
                ['title', 'string', 'max' => 256],
                ['shop_name', 'string', 'max' => 20],
                [['shop_url', 'shop_agency', 'shop_email'], 'string', 'max' => 255],
                [['brands', 'categories', 'items', 'status', 'asAttachment'], 'safe'],
                [['to_excel', 'shop_cpa', 'delivery_free_from', 'all_delivery_options_cost', 'delivery_options_cost'], 'integer'],
                [['id', 'title'], 'safe'],
        ];
    }

    public function checkExists($attribute) {
        if (!class_exists($this->$attribute)) {
            $this->addError($attribute, Yii::t('admin', 'Класс не существует'));
        }
    }

    public function attributeLabels() {
        return [
            'id' => Yii::t('admin/yml', 'ID'),
            'title' => Yii::t('admin/yml', 'Название выгрузки'),
            'brands' => Yii::t('admin/yml', 'Бренды'),
            'categories' => Yii::t('admin/yml', 'Категории'),
            'items' => Yii::t('admin/yml', 'Элементы'),
            'class' => Yii::t('admin/yml', 'Класс'),
            'count' => Yii::t('admin/yml', 'Кол-во загружаемых предложений (0 - загрузить все)'),
            'shop_name' => Yii::t('admin/yml', 'Короткое название магазина (не более 20 символов)'),
            'shop_company' => Yii::t('admin/yml', 'Полное наименование компании, владеющей магазином. Не публикуется, используется для внутренней идентификации'),
            'shop_url' => Yii::t('admin/yml', 'URL главной страницы магазина'),
            'to_excel' => Yii::t('admin/yml', 'Тип экспорта: YML или Excel'),
            'status' => Yii::t('admin/yml', 'Выгружать товары со статусом'),
            'shop_agency' => Yii::t(
                    'admin/yml', 'Наименование агентства, которое оказывает техническую поддержку магазину и отвечает за работоспособность сайта'
            ),
            'shop_email' => Yii::t(
                    'admin/yml', 'Контактный адрес разработчиков CMS или агентства, осуществляющего техподдержку'
            ),
            'shop_cpa' => Yii::t('admin/yml', 'Участие товарных предложений в программе «Покупка на Маркете»'),
            'all_delivery_options_cost' => Yii::t('admin/yml', 'Общая стоимость доставки <delivery-options><option cost="..."/></delivery-options>'),
            'all_delivery_options_days' => Yii::t('admin/yml', 'Общая срок доставки в рабочих днях <delivery-options><option days="..."/></delivery-options>'),
            'delivery_free_from' => Yii::t('admin/yml', 'Бесплатная доставка от (Если выполняется это условие, то к товару применяются индивидуальные условия доставки)'),
            'delivery_options_cost' => Yii::t('admin/yml', 'Индивидуальная стоимость доставки <delivery-options><option cost="..."/></delivery-options>'),
            'delivery_options_days' => Yii::t('admin/yml', 'Индивидуальный срок доставки в рабочих днях <delivery-options><option days="..."/></delivery-options>'),
            'asAttachment' => Yii::t('admin/yml', 'Загрузить файл .xlsx на локальное устройство'),
        ];
    }

    public function afterFind() {
        $data = json_decode($this->data);

        $this->brands = $data->brands;
        $this->class = $data->class;
        $this->count = $data->count;
        $this->categories = $data->categories;
        $this->items = $data->items;
        $this->to_excel = $data->to_excel;
        $this->status = $data->status;
        $this->shop_name = $data->shop_name;
        $this->shop_company = $data->shop_company;
        $this->shop_url = $data->shop_url;
        $this->shop_agency = $data->shop_agency;
        $this->shop_email = $data->shop_email;
        $this->shop_cpa = $data->shop_cpa;
        $this->all_delivery_options_cost = $data->all_delivery_options_cost;
        $this->all_delivery_options_days = $data->all_delivery_options_days;
        $this->delivery_free_from = $data->delivery_free_from;
        $this->delivery_options_cost = $data->delivery_options_cost;
        $this->delivery_options_days = $data->delivery_options_days;
        $this->asAttachment = $data->asAttachment;

        parent::afterFind();
    }

    public function beforeValidate() {

        $data = [
            'brands' => $this->brands,
            'class' => $this->class,
            'count' => $this->count,
            'categories' => $this->categories,
            'items' => $this->items,
            'to_excel' => $this->to_excel,
            'status' => $this->status,
            'shop_name' => $this->shop_name,
            'shop_company' => $this->shop_company,
            'shop_url' => $this->shop_url,
            'shop_agency' => $this->shop_agency,
            'shop_email' => $this->shop_email,
            'shop_cpa' => $this->shop_cpa,
            'all_delivery_options_cost' => $this->all_delivery_options_cost,
            'all_delivery_options_days' => $this->all_delivery_options_days,
            'delivery_free_from' => $this->delivery_free_from,
            'delivery_options_cost' => $this->delivery_options_cost,
            'delivery_options_days' => $this->delivery_options_days,
            'asAttachment' => $this->asAttachment,
        ];
        $this->data = json_encode($data);

        return parent::beforeValidate();
    }

    private function listCategories() {
        $query = Category::find();
        if ($this->status != '') {
            $query->andFilterWhere(['=', 'status', (int) $this->status]);
        }
        if (!empty($this->categories)) {
            $query->andFilterWhere(['in', 'id', (array) $this->categories]);
        }

        return $query->all();
    }

    private function listItems() {
        $query = \admin\modules\catalog\models\Item::find()->with(['category'])->orderBy(['brand_id' => SORT_ASC, 'name' => SORT_ASC]);

        $flag = false;

        if ($this->status != '') {
            $query->andFilterWhere(['=', 'status', (int) $this->status]);
        }

        if (!empty($this->categories)) {
            $query->andFilterWhere(['in', 'category_id', (array) $this->categories]);
            $flag = true;
        }

        if (!empty($this->brands)) {
            $query->andFilterWhere(['in', 'brand_id', (array) $this->brands]);
            $flag = true;
        }

        if (!empty($this->items)) {
            if ($flag == true) {
                $query->orFilterWhere(['in', 'id', (array) $this->items]);
            } else {
                $query->andFilterWhere(['in', 'id', (array) $this->items]);
            }
        }

        $items = $query->all();

        $_items = [];
        foreach ($items as $item) {
            if ($this->count > 0 && $count >= $this->count) {
                break;
            }
            $count++;

            $_items[] = $this->getItem($item);
        }
        return $_items;
    }

    public function saveToYmlFile() {

        $categories = $this->listCategories();
        $items = $this->listItems();

        $file_tmp = Yii::getAlias('@webroot') . '/exports_yml/yml_' . $this->shop_name . '_tmp.xml';
        $file = Yii::getAlias('@webroot') . '/exports_yml/yml_' . $this->shop_name . '.xml';

        FileHelper::createDirectory(Yii::getAlias('@webroot') . '/exports_yml', 0777);

        file_put_contents($file_tmp, Yii::$app->controller->renderPartial(
                        '@admin/modules/yml/views/export/yml.php', [
                    'xmlHeader' => '<?xml version="1.0" encoding="UTF-8"?>' . PHP_EOL . '<!DOCTYPE yml_catalog SYSTEM "shops.dtd">' . PHP_EOL,
                    'model' => $this,
                    'currencies' => ['RUB'],
                    'categories' => $categories,
                    'items' => $items,
                        ]
        ));
        $file_old = Yii::getAlias('@webroot') . '/exports_yml/yml_' . $this->shop_name . '_' . date('Y_m_d_H_i_s') . '.xml';
        if (file_exists($file)) {
            rename($file, $file_old);
        }
        rename($file_tmp, $file);
        return $file;
    }

    public function getItem($item) {
        throw new Exception("Must be implemented");
    }

    public function saveToExcelFile() {

        $items = $this->listItems();


admin/modules/yml/controllers/ExportController.php
<?

namespace admin\modules\yml\controllers;

use Yii;
use yii\data\ActiveDataProvider;
use yii\widgets\ActiveForm;
use yii\helpers\Json;

use admin\modules\yml\models\Export;
use admin\modules\yml\helpers\WebConsole;
use admin\models\Setting;
use admin\modules\catalog\models\Item;

class ExportController extends \admin\base\admin\Controller {

    public function actionIndex() {
        $data = new ActiveDataProvider([
            'query' => Export::find(),
        ]);
        return $this->render('index', [
                    'data' => $data
        ]);
    }

    public function actionCreate($slug = null) {
        $model = new Export();

        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            } else {
                if ($model->save()) {
                    $this->flash('success', Yii::t('admin/yml', 'Экспорт создан'));
                    return $this->redirect(['/admin/' . $this->module->id . '/export']);
                } else {
                    $this->flash('error', Yii::t('admin', 'Ошибка. {0}', $model->formatErrors()));
                    return $this->refresh();
                }
            }
        } else {
            if ($slug) {
                $model->slug = $slug;
            }

            $model->shop_name = Setting::get('contact_name');
            $model->shop_company = Setting::get('contact_name');
            $model->shop_url = Setting::get('contact_url');

            return $this->render('create', [
                        'model' => $model
            ]);
        }
    }

    public function actionEdit($id) {
        $model = Export::findOne($id);

        if ($model === null) {
            $this->flash('error', Yii::t('admin', 'Запись не найдена'));
            return $this->redirect(['/admin/' . $this->module->id . '/export']);
        }

        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            } else {
                if ($model->save()) {
                    $this->flash('success', Yii::t('admin/yml', 'Экспорт обновлен'));
                } else {
                    $this->flash('error', Yii::t('admin', 'Ошибка при обновлении записи. {0}', $model->formatErrors()));
                }
                return $this->refresh();
            }
        } else {
            return $this->render('edit', [
                        'model' => $model
            ]);
        }
    }

    public function actionDelete($id) {
        if (($model = Export::findOne($id))) {
            $model->delete();
        } else {
            $this->error = Yii::t('admin', 'Запись не найдена');
        }
        return $this->formatResponse(Yii::t('admin/yml', 'Экспорт удален'));
    }

    public function actionExecute($id) {

        if (($model = Export::findOne($id))) {
            $result = WebConsole::ymlExport($id);
        } else {
            $this->error = Yii::t('admin', 'Запись не найдена');
        }
        return $this->formatResponse($result, true, true);
    }

    public function actionDefaultExcelExecute() {

        $model = new \admin\modules\yml\external_export\Shop();
        $model->title = Setting::get('contact_name');
        $model->to_excel = true;
        $model->asAttachment = true;

        $model->saveToExcelFile();
    }

    public function actionItemsJson() {

        $category_id = Yii::$app->request->post('category_id');
        $brand_id =  Yii::$app->request->post('brand_id');


        $items = Item::find()->select(['id', 'name', 'article'])->where(['and', ['category_id' => $category_id],['brand_id' => $brand_id]])->asArray()->all();


        return Json::encode([   
                'status' => 'success',
                'items' => $items
            ]);
        
    }

}

admin/modules/yml/views/export/_form.php
<?

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use admin\modules\catalog\models\Brand;
use admin\modules\catalog\models\Category;
use admin\modules\catalog\models\Item;
use admin\modules\yml\YmlModule;
use yii\web\View;
use admin\assets\AdminModuleAsset;

AdminModuleAsset::register($this);

$module = $this->context->module->id;
?>
<?
$form = ActiveForm::begin([
            'enableAjaxValidation' => true,
            'options' => ['class' => 'model-form']
        ]);
?>

<?=
$form->field($model, 'to_excel')->hiddenInput()->label('');
$js[] = "$('#a_YML').on('click', function(){
            $('#export-to_excel').val(0)});";
$js[] = "$('#a_Excel').on('click', function(){
            $('#export-to_excel').val(1)});";
$this->registerJs(implode(PHP_EOL, $js), View::POS_READY);
?>   
<?
$_items = Item::find()->select(['id', 'category_id', 'brand_id'])->where(['in', 'id', (array) $model->items])->asArray()->all();
?>   




<div class="row mb-30">
    <div class="col-sm-8">
        <?= $form->field($model, 'title') ?>
        <?= $form->field($model, 'class') ?>
        <?= $form->field($model, 'status')->dropDownList(['' => Yii::t('admin/yml', '(все)'), '0' => Yii::t('admin', 'не активные'), '1' => Yii::t('admin/yml', 'активные')]) ?>
        <?= $form->field($model, 'count'); ?>        
    </div>
    <div class="col-sm-1">

    </div>
    <div class="col-sm-3">
        <div class="form-group">
            <label class="control-label">Столбцы в excel</label><br>
            <?
            $count = 0;
            foreach (YmlModule::getFields() as $field) {
                $count++;
                if (is_array($field)) {
                    echo $count . '.  ' . $field['attribute'] . '<br>';
                } else {
                    echo $count . '.  ' . $field . '<br>';
                }
            }
            ?>
            <div class="help-block"></div>
        </div>
    </div>
</div>
<div class="row mb-30">
    <div class="col-sm-12">
        <small>
            Укажите бренды, категории или отдельные элементы каталога, которые подлежат выгрузке. При выборе категории и бренда выгружаться будут элементы, которые принадлежат и категории и бренду.
            <br>
            Отдельные элементы будут выгружаться, даже если они не пренадлежат бренду или категории. Если бренд или категория не указаны, то будут выгружены все элементы каталога.
        </small>
    </div>
</div>
<div class="row mb-30">
    <div class="col-sm-4">
        <?= $form->field($model, 'brands')->checkboxList(Brand::listAll('id', 'title'), ['separator' => '<br>']); ?>
    </div>
    <div class="col-sm-4">
        <?= $form->field($model, 'categories')->checkboxList(Category::listAll('id', 'title'), ['separator' => '<br>']); ?>
    </div>
    <div id="export-catalog" class="col-sm-4">
        <div class="form-group">
            <label class="control-label">Отдельные элементы каталога</label><br>
        </div>
        <input type="hidden" name="Export[items][]">
        <?
        $tree = Category::tree('catalog', true);
        foreach ($tree->children as $node) {
            echo $node->title . '<br/>';
            foreach ($node->children as $node) {
                echo '&nbsp;&nbsp;&nbsp;' . $node->title . '<br>';

                $subQuery = Item::find()->select('brand_id')->where(['category_id' => $node->id]);
                $query = Brand::find()->status(Brand::STATUS_ON)->join('INNER JOIN', ['i' => $subQuery], 'i.brand_id = ' . Brand::tableName() . '.id');

                if (!empty($options['where'])) {
                    $query->andWhere(['is not', 'image', null]);
                }
                if (!empty($options['orderBy'])) {
                    $query->orderBy($options['orderBy']);
                } else {
                    $query->orderBy(['title' => SORT_ASC]);
                }
                $brands = $query->all();
                foreach ($brands as $brand) {

                    $str = "";
                    $expand = "false";
                    foreach ($_items as $_item) {
                        if ($_item['category_id'] == $node->id && $_item['brand_id'] == $brand->id) {
                            $expand = "true";
                        }
                    }
                    if ($expand == "true") {
                        $str .= '<span>';
                        $items = Item::find()->select(['id', 'name', 'article'])->where(['and', ['category_id' => $node->id], ['brand_id' => $brand->id]])->asArray()->all();
                        foreach ($items as $item) {
                            $checked = "";
                            foreach ($_items as $_item) {
                                if ($_item['id'] == $item['id']) {
                                    $checked = 'checked';
                                }
                            }
                            $str .= '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input ' . $checked . ' type="checkbox" name="Export[items][]" value="' . $item['id'] . '">' . $item['name'] . ' ' . $item['article'] . '<br>';
                        }
                        $str .= '</span>';
                    } else {
                        $str .= '<span></span>';
                    }



                    echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="dotted" data-expand="' . $expand . '" data-category-id="' . $node->id . '" data-brand-id="' . $brand->id . '">' . $brand->title . '<br></span>';
                    echo $str;
                }
            }
        }
        ?>
    </div>
</div>
<div class="nav-tabs-custom">
    <ul class="nav nav-tabs">
        <li class="<?= $model->to_excel ? '' : 'active' ?>"><a href="#tab_YML" id="a_YML" data-toggle="tab" aria-expanded="true"><?= Yii::t('admin/yml', 'YML') ?></a></li>
        <li class="<?= $model->to_excel ? 'active' : '' ?>"><a href="#tab_Excel" id="a_Excel" data-toggle="tab" aria-expanded="false"><?= Yii::t('admin/yml', 'Excel') ?></a></li>                    
    </ul>
    <div class="tab-content">
        <div class="tab-pane <?= $model->to_excel ? '' : 'active' ?>" id="tab_YML">
            <div class="row mt-20 mb-40">
                <div class="col-sm-12">
                    <?= Yii::t('admin/yml', 'Текущий файл:') ?> <a href="<?= '/exports_yml/yml_' . $model->shop_name . '.xml' ?>" target="_blank" title="<?= '/exports_yml/yml_' . $model->shop_name . '.xml' ?>"><?= Yii::$app->request->serverName . '/exports_yml/yml_' . $model->shop_name . '.xml' ?> <i class="fa fa-external-link"></i></a>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="row">
                        <div class="col-sm-12">
                            <?= $form->field($model, 'shop_name'); ?>
                        </div> 
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <?= $form->field($model, 'shop_company'); ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <?= $form->field($model, 'shop_url'); ?>
                        </div>
                    </div>
                </div>
                <div class="col-sm-2">
                </div> 
                <div class="col-sm-4">
                    <div class="row">
                        <div class="col-sm-12">
                            <?= $form->field($model, 'shop_agency'); ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <?= $form->field($model, 'shop_email'); ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <?= $form->field($model, 'shop_cpa')->checkbox() ?>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3">
                    <?= $form->field($model, 'all_delivery_options_cost'); ?>
                </div>
                <div class="col-sm-3">
                    <?= $form->field($model, 'all_delivery_options_days'); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <?= $form->field($model, 'delivery_free_from'); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3">
                    <?= $form->field($model, 'delivery_options_cost'); ?>
                </div>
                <div class="col-sm-3">
                    <?= $form->field($model, 'delivery_options_days'); ?>
                </div>
            </div>
        </div>
        <div class="tab-pane <?= $model->to_excel ? 'active' : '' ?>" id="tab_Excel">
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'asAttachment')->checkbox(); ?>                         
                </div>
            </div>
        </div>                     
    </div>            
</div>
<div class="row">
    <div class="col-md-6">
        <?= Html::submitButton(Yii::t('admin', 'Сохранить'), ['class' => 'btn btn-primary']) ?>
    </div>
    <div class="col-md-6 text-right">
        <a class="btn btn-success" href="<?= Url::to(['/admin/' . $module . '/export/execute', 'id' => $model->primaryKey]) ?>" title="<?= Yii::t('admin', 'Выполнить экспорт') ?>"><span class="fa fa-arrow-right"></span> <?= Yii::t('admin', 'Выполнить экспорт') ?></a>
    </div>
</div>
<? ActiveForm::end(); ?>

admin/modules/yml/views/export/_menu.php
<?

use yii\helpers\Url;

$action = $this->context->action->id;
$module = $this->context->module->id;
?>
<ul class="nav nav-pills">
    <li <?= ($action === 'index') ? 'class="active"' : '' ?>>
        <a href="<?= Url::to('/admin/' . $module . '/export') ?>">
            <? if ($action === 'edit') : ?>
                <i class="fa fa-chevron-left fs-12"></i>
            <? endif; ?>
            <?= Yii::t('admin/yml', 'Список экспортов') ?>
        </a>
    </li>
    <li <?= ($action === 'create') ? 'class="active"' : '' ?>><a href="<?= Url::to(['/admin/' . $module . '/export/create']) ?>"><?= Yii::t('admin', 'Создать') ?></a></li>
</ul>
<br/>

admin/modules/yml/views/export/create.php
<?
$this->title = Yii::t('admin/yml', 'Создать экспорт');
?>
<?= $this->render('_menu') ?>
<?= $this->render('_form', ['model' => $model]) ?>

admin/modules/yml/views/export/edit.php
<?
$this->title = Yii::t('admin/yml', 'Редактировать экспорт');
?>
<?= $this->render('_menu') ?>
<?= $this->render('_form', ['model' => $model]) ?>

admin/modules/yml/views/export/index.php
<?

use yii\helpers\Url;

$this->title = Yii::t('admin/yml', 'Экспорты');

$module = $this->context->module->id;
?>

<?= $this->render('_menu') ?>

<? if ($data->count > 0) : ?>
    <table class="table table-hover">
        <thead>
            <tr>
                <th width="50">#</th>
                <th><?= Yii::t('admin', 'Название') ?></th>
                <th><?= Yii::t('admin', 'URL') ?></th>
                <th width="30"></th>
            </tr>
        </thead>
        <tbody>
            <? foreach ($data->models as $item) : ?>
                <tr>
                    <td><?= $item->primaryKey ?></td>
                    <td><a href="<?= Url::to(['/admin/' . $module . '/export/edit', 'id' => $item->primaryKey]) ?>"><?= $item->title ?></a></td>
                    <td><a target="_blank" href="<?= Url::to(['/admin/' . $module . '/export', 'id' => $item->primaryKey]) ?>"><?= Url::to(['/admin/' . $module . '/export', 'id' => $item->primaryKey]) ?></a></td>
                    <td><a href="<?= Url::to(['/admin/' . $module . '/export/delete', 'id' => $item->primaryKey]) ?>" class="fa fa-times text-red" title="<?= Yii::t('admin', 'Удалить запись') ?>"></a></td>
                </tr>
            <? endforeach; ?>
        </tbody>
    </table>
    <?=
    yii\widgets\LinkPager::widget([
        'pagination' => $data->pagination
    ])
    ?>
<? else : ?>
    <p><?= Yii::t('admin', 'Записи не найдены') ?></p>
<? endif; ?>

admin/modules/yml/views/export/yml.php
<?

use yii\helpers\Url;
use admin\modules\yml\YmlModule;

$marketcategories = [];
?>
<?= $xmlHeader; ?>
<yml_catalog date="<?= date('Y-m-d H:i'); ?>">
    <shop>
        <name><?= $model->shop_name; ?></name>
        <company><?= $model->shop_company; ?></company>
        <url><?= $model->shop_url; ?></url>
        <platform><?= \admin\AdminModule::NAME ?></platform>
        <version><?= \admin\AdminModule::VERSION ?></version>
        <agency><?= $model->shop_agency; ?></agency>
        <email><?= $model->shop_email; ?></email>
        <currencies>
            <? foreach ($currencies as $currency): ?>
                <currency id="<?= $currency; ?>" <?= $currency === 'RUB' ? 'rate="1"' : ''; ?>/>
            <? endforeach; ?>
        </currencies>
        <categories>
            <? foreach ($categories as $category): ?>
                <category id="<?= $category->id ?>"><?= $category->title; ?></category>
            <? endforeach; ?>
        </categories>
        <delivery-options>
            <option cost="<?= $model->all_delivery_options_cost ?>" days="<?= $model->all_delivery_options_days ?>"/>
        </delivery-options>
        <cpa><?= $model->shop_cpa; ?></cpa>
        <offers>
            <? foreach ($items as $item) : ?>
                <offer id="<?= $item->id ?>" type="vendor.model" available="<?= $item->available ? 'true' : 'false'; ?>">
                    <url><?= $item->url ?></url>
                    <price><?= $item->price ?></price>
                    <?
                    if ($item->old_price > $item->price) {
                        ?>
                        <oldprice><?= $item->old_price ?></oldprice>
                        <?
                    }
                    ?>
                    <currencyId><?= 'RUB' ?></currencyId>
                    <categoryId><?= $item->category->id; ?></categoryId>
                    <store>true</store>
                    <pickup>true</pickup>
                    <delivery>true</delivery>
                    <?
                    if ($item->price < $model->delivery_free_from) {
                        ?>
                        <delivery-options>
                            <option cost="<?= $model->delivery_options_cost ?>" days="<?= $model->delivery_options_days ?>"/>
                        </delivery-options>
                        <?
                    }
                    ?>
                    <? foreach ($item->photos as $photo) { ?>
                        <picture><?= $photo ?></picture>                       
                    <? } ?>
                    <typePrefix><?= $item->type ?></typePrefix>
                    <model><?= $item->name ?></model>
                    <vendor><?= $item->brand ?></vendor>
                    <market_category><?= $item->marketcategory ?></market_category>
                    <description><?= htmlspecialchars(strip_tags($item->description)); ?></description>
                    <?
                    //Доп.параметры   
                    foreach (YmlModule::getAdditionalFields(true) as $field) {
                        if (!empty($item->data[$field['attribute']])) {
                            ?>
                            <param name="<?= $field['header'] ?>"><?= htmlspecialchars(strip_tags($item->data[$field['attribute']])) ?></param>
                            <?
                        }
                    }
                    ?>                 
                </offer>
            <? endforeach; ?>
        </offers>
    </shop>
</yml_catalog>